// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbvhjvwkvaukstkdhvno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidmhqdndrdmF1a3N0a2Rodm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTQ2NjUsImV4cCI6MjA2ODkzMDY2NX0.uXOpRS_K9YQMhjLUQ1Btsuj46OJKDFvCJJ53xNLxyrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});